'use strict';
/* validate.js — input validation and display-name sanitizing for the weekly leaderboard.
 * The game is for all ages, so names are strictly limited and filtered. This is a
 * basic safety net, not a complete moderation system: extend BLOCKED as needed.
 */

const NAME_MAX = 14;
const MAX_SCORE = 500;
const GROUP_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no 0/O/1/I

// Common profanity and sexual/violent terms. Matched against a normalized form
// (lowercase, leetspeak undone, separators removed) so "f.u.c.k" and "sh1t" are caught.
const BLOCKED = [
  'fuck', 'shit', 'bitch', 'cunt', 'dick', 'cock', 'pussy', 'whore', 'slut', 'bastard',
  'asshole', 'nazi', 'hitler', 'rape', 'porn', 'sex', 'nude', 'kill', 'suicide', 'molest'
];

const LEET = { 0: 'o', 1: 'i', 3: 'e', 4: 'a', 5: 's', 7: 't', 8: 'b', 9: 'g', '@': 'a', $: 's', '!': 'i' };

function normalizeForFilter(text) {
  return String(text)
    .toLowerCase()
    .replace(/[0134578 9@$!]/g, (c) => (c === ' ' ? '' : LEET[c] || c))
    .replace(/[^a-z]/g, '')
    .replace(/(.)\1+/g, '$1'); // collapse repeats: "fuuuck" -> "fuck"
}

function isBlockedName(text) {
  const flat = normalizeForFilter(text);
  const squashed = BLOCKED.map((w) => w.replace(/(.)\1+/g, '$1'));
  return squashed.some((w) => flat.includes(w));
}

/* Returns a safe display name: letters, digits, space, underscore and hyphen only,
 * 1-14 characters, with anything filtered replaced by "Player" + 4 digits derived
 * from the device id (stable, so the same device keeps the same fallback name). */
function sanitizeName(raw, deviceId) {
  const normalized = String(raw == null ? '' : raw).normalize('NFKC');
  // Filter the raw text too: symbols like "!" and "@" are leetspeak and would be
  // stripped before the check otherwise ("b!tch" -> "btch").
  if (isBlockedName(normalized)) return fallbackName(deviceId);
  const cleaned = normalized
    .replace(/[^A-Za-z0-9 _-]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, NAME_MAX)
    .trim();
  if (cleaned && !isBlockedName(cleaned)) return cleaned;
  return fallbackName(deviceId);
}

function fallbackName(deviceId) {
  let h = 0;
  const s = String(deviceId || '');
  for (let i = 0; i < s.length; i++) h = (Math.imul(h, 31) + s.charCodeAt(i)) >>> 0;
  return 'Player' + String(h % 10000).padStart(4, '0');
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const isDeviceId = (v) => typeof v === 'string' && UUID_RE.test(v);
// 256-bit random secret, base64url or hex, generated by the client.
const isDeviceKey = (v) => typeof v === 'string' && /^[A-Za-z0-9_-]{32,64}$/.test(v);
const isGroupCode = (v) => typeof v === 'string' && new RegExp('^[' + GROUP_CODE_ALPHABET + ']{6}$').test(v);
const isWeekId = (v) => typeof v === 'string' && /^\d{4}-W(0[1-9]|[1-4]\d|5[0-3])$/.test(v);

function isScore(v) { return Number.isInteger(v) && v >= 1 && v <= MAX_SCORE; }

function randomGroupCode(randomInt) {
  let code = '';
  for (let i = 0; i < 6; i++) code += GROUP_CODE_ALPHABET[randomInt(GROUP_CODE_ALPHABET.length)];
  return code;
}

module.exports = {
  NAME_MAX, MAX_SCORE, GROUP_CODE_ALPHABET,
  sanitizeName, fallbackName, isBlockedName,
  isDeviceId, isDeviceKey, isGroupCode, isWeekId, isScore, randomGroupCode
};
